global using System.Net.Http;
global using System.Net.Http.Json;
global using System.Text;
global using System.Threading.Tasks;
global using System.Diagnostics;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.Mvc.NewtonsoftJson;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Authorization;